import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, GitBranch } from "lucide-react";
import { canManageInventory, getOrganizationContext } from "@/lib/auth/organization";
import { deactivateVariant, saveVariant } from "./actions";

const input="h-10 w-full rounded-lg border border-black/10 bg-white px-3 text-sm outline-none focus:border-[#39705b]";
type Attribute={id:string;name:string;product_attribute_values:Array<{id:string;value:string;position:number}>};
type VariantValue={attribute_id:string;value_id:string;product_attribute_values:{value?:string}|Array<{value?:string}>|null};

export default async function ProductVariantsPage({params,searchParams}:PageProps<"/inventario/[id]/variantes">){
  const[{id},query,context]=await Promise.all([params,searchParams,getOrganizationContext()]);
  const[{data:product},{data:attributes,error:attributesError},{data:variants,error:variantsError}]=await Promise.all([
    context.supabase.from("products").select("id,name,sku,cost,price").eq("id",id).eq("organization_id",context.organization.id).eq("active",true).maybeSingle(),
    context.supabase.from("product_attributes").select("id,name,product_attribute_values(id,value,position)").eq("organization_id",context.organization.id).eq("active",true).eq("product_attribute_values.active",true).order("name"),
    context.supabase.from("product_variants").select("id,name,sku,barcode,cost,price,product_variant_values(attribute_id,value_id,product_attribute_values(value))").eq("organization_id",context.organization.id).eq("product_id",id).eq("active",true).order("name"),
  ]);
  if(!product)notFound();if(attributesError||variantsError)throw new Error("No se pudieron cargar las variantes.");
  const canEdit=canManageInventory(context.role),notice=query.saved?"Variante guardada correctamente.":query.deactivated?"Variante desactivada correctamente.":null,alert=query.error==="permissions"?"No tienes permiso para modificar variantes.":query.error==="duplicate"?"El SKU o código de barras ya está registrado.":query.error?"No se pudo completar la operación.":null,currency=context.organization.currency_code==="GTQ"?"Q":context.organization.currency_code;
  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div><p className="font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Variantes de producto</p></div><Link href="/inventario" className="flex items-center gap-2"><ArrowLeft size={16}/>Inventario</Link></div></header><div className="mx-auto max-w-6xl space-y-6 px-6 py-9"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#517064]">Producto</p><h1 className="mt-2 text-4xl font-bold">{product.name}</h1><p className="mt-2 text-[#68766f]">{product.sku||"Sin SKU"} · Precio base {currency} {Number(product.price).toFixed(2)}</p></div>{notice&&<p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{notice}</p>}{alert&&<p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-800">{alert}</p>}{canEdit&&<VariantForm product={product} attributes={attributes??[]}/>}<section className="overflow-hidden rounded-2xl border border-black/8 bg-white"><h2 className="flex items-center gap-2 border-b p-5 text-xl font-bold"><GitBranch size={20}/>Variantes activas <span className="ml-auto rounded-full bg-[#edf0eb] px-2 py-1 text-xs">{variants?.length??0}</span></h2><div className="divide-y">{variants?.map(variant=>{const values=(variant.product_variant_values??[]) as VariantValue[],selected=new Map(values.map(value=>[value.attribute_id,value.value_id]));return <details key={variant.id} className="group"><summary className="flex cursor-pointer list-none flex-col justify-between gap-2 p-5 hover:bg-[#fafbf8] sm:flex-row sm:items-center"><span><strong>{variant.name}</strong><small className="mt-1 block text-[#75837b]">{values.map(item=>{const value=Array.isArray(item.product_attribute_values)?item.product_attribute_values[0]?.value:item.product_attribute_values?.value;return value}).filter(Boolean).join(" · ")||"Sin atributos"} · {variant.sku||"Sin SKU"}</small></span><strong>{currency} {Number(variant.price??product.price).toFixed(2)}</strong></summary>{canEdit&&<div className="border-t bg-[#f8f9f6] p-5"><VariantForm product={product} attributes={attributes??[]} variant={{...variant,selected}}/><form action={deactivateVariant} className="mt-3 text-right"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="variantId" value={variant.id}/><button className="text-sm font-bold text-red-700">Desactivar variante</button></form></div>}</details>})}{!variants?.length&&<p className="p-12 text-center text-sm text-[#75837b]">Aún no hay variantes para este producto.</p>}</div></section></div></main>;
}

function VariantForm({product,attributes,variant}:{product:{id:string;cost:number|string;price:number|string};attributes:Attribute[];variant?:{id:string;name:string;sku:string|null;barcode:string|null;cost:number|string|null;price:number|string|null;selected:Map<string,string>}}){return <form action={saveVariant} className="grid gap-4 rounded-2xl border border-black/8 bg-white p-5 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="productId" value={product.id}/>{variant&&<input type="hidden" name="variantId" value={variant.id}/>}<label className="md:col-span-2"><span className="mb-1 block text-sm font-semibold">Nombre *</span><input name="name" required defaultValue={variant?.name} placeholder="Ej. Camisa roja mediana" className={input}/></label><Field name="sku" label="SKU" value={variant?.sku}/><Field name="barcode" label="Código de barras" value={variant?.barcode}/><Field name="cost" label="Costo propio (opcional)" value={variant?.cost} type="number" placeholder={String(product.cost)}/><Field name="price" label="Precio propio (opcional)" value={variant?.price} type="number" placeholder={String(product.price)}/>{attributes.map(attribute=><label key={attribute.id}><input type="hidden" name="attributeId" value={attribute.id}/><span className="mb-1 block text-sm font-semibold">{attribute.name}</span><select name={`value_${attribute.id}`} required defaultValue={variant?.selected.get(attribute.id)??""} className={input}><option value="" disabled>Selecciona un valor</option>{attribute.product_attribute_values.sort((a,b)=>a.position-b.position||a.value.localeCompare(b.value)).map(value=><option key={value.id} value={value.id}>{value.value}</option>)}</select></label>)}<div className="flex items-end md:col-span-2 xl:col-span-4"><button disabled={!attributes.length} className="h-11 rounded-lg bg-[#d7f36b] px-6 font-bold text-[#163f32] disabled:cursor-not-allowed disabled:opacity-50">{variant?"Guardar cambios":"Crear variante"}</button>{!attributes.length&&<Link href="/inventario/catalogos#attributes" className="ml-4 text-sm font-bold text-[#285645] underline">Primero crea atributos y valores</Link>}</div></form>}
function Field({name,label,value,type="text",placeholder}:{name:string;label:string;value?:string|number|null;type?:string;placeholder?:string}){return <label><span className="mb-1 block text-sm font-semibold">{label}</span><input name={name} type={type} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} defaultValue={value??""} placeholder={placeholder} className={input}/></label>}
