import Link from "next/link";
import { ArrowLeft, CheckCircle2, MoveRight } from "lucide-react";
import { canManageInventory, getOrganizationContext } from "@/lib/auth/organization";
import { TransferForm } from "./transfer-form";

export default async function TransfersPage({ searchParams }: PageProps<"/transferencias">) {
  const context = await getOrganizationContext();
  const params = await searchParams;
  const allowed = canManageInventory(context.role);
  const [{ data: products }, { data: transfers }] = await Promise.all([
    context.supabase.from("products").select("id, name, sku, inventory_levels(location_id, quantity), product_variants(id,name,sku,active,variant_inventory_levels(location_id,quantity))").eq("organization_id", context.organization.id).eq("active", true).order("name"),
    context.supabase.from("inventory_transfers").select("id, reference, transferred_at, source:locations!inventory_transfers_source_location_id_fkey(name), destination:locations!inventory_transfers_destination_location_id_fkey(name), inventory_transfer_items(quantity)").eq("organization_id", context.organization.id).order("transferred_at", { ascending: false }).limit(10),
  ]);
  const normalizedProducts = (products ?? []).flatMap((product) => [{ id: product.id,variantId:null as string|null, name: product.name, sku: product.sku, levels: (product.inventory_levels as Array<{ location_id: string; quantity: string | number }> ?? []).map((level) => ({ locationId: level.location_id, quantity: Number(level.quantity) })) },...product.product_variants.filter(variant=>variant.active).map(variant=>({id:product.id,variantId:variant.id,name:`${product.name} · ${variant.name}`,sku:variant.sku??product.sku,levels:variant.variant_inventory_levels.map(level=>({locationId:level.location_id,quantity:Number(level.quantity)}))}))]);

  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><div><p className="text-lg font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Movimientos entre sucursales</p></div><Link href="/" className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold"><ArrowLeft size={16} /> Panel</Link></div></header><div className="mx-auto max-w-7xl space-y-7 px-6 py-9 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#517064]">Inventario</p><h1 className="mt-2 text-4xl font-bold tracking-[-0.04em]">Transferencias</h1></div>{params.completed && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 font-semibold text-emerald-700"><CheckCircle2 size={19} /> Transferencia completada y existencias actualizadas.</p>}{context.locations.length < 2 ? <div className="rounded-2xl bg-white p-10 text-center"><h2 className="font-bold">Se necesitan dos sucursales activas</h2><Link href="/sucursales" className="mt-3 inline-block font-bold text-[#285645]">Administrar sucursales</Link></div> : allowed ? <TransferForm locations={context.locations} products={normalizedProducts} selectedLocationId={context.location.id} /> : <div className="rounded-2xl bg-white p-10 text-center text-red-700">Tu rol no permite transferir inventario.</div>}
      <section className="rounded-2xl border border-black/8 bg-white"><h2 className="border-b border-black/8 p-5 font-bold">Transferencias recientes</h2><div className="divide-y divide-black/8">{!transfers?.length && <p className="p-10 text-center text-sm text-[#728078]">Todavía no hay transferencias.</p>}{transfers?.map((transfer) => { const sourceValue = transfer.source as { name?: string } | Array<{ name?: string }> | null; const destinationValue = transfer.destination as { name?: string } | Array<{ name?: string }> | null; const source = Array.isArray(sourceValue) ? sourceValue[0] : sourceValue; const destination = Array.isArray(destinationValue) ? destinationValue[0] : destinationValue; const itemCount = (transfer.inventory_transfer_items as Array<{ quantity: string | number }> ?? []).length; return <article key={transfer.id} className="grid gap-3 p-4 text-sm md:grid-cols-[1fr_auto_auto] md:items-center"><div><p className="font-bold">{transfer.reference || "Sin referencia"}</p><p className="mt-1 text-xs text-[#75837b]">{new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Guatemala" }).format(new Date(transfer.transferred_at))}</p></div><p className="flex items-center gap-2 font-semibold">{source?.name} <MoveRight size={16} /> {destination?.name}</p><span className="rounded-full bg-[#edf0eb] px-3 py-1 text-xs font-bold">{itemCount} productos</span></article>; })}</div></section>
    </div></main>;
}
