"use client";

import { useActionState, useMemo, useState } from "react";
import { ArrowRight, Minus, PackagePlus, Plus } from "lucide-react";
import { createTransfer, type TransferState } from "./actions";

type Location = { id: string; name: string };
type Product = { id: string; name: string; sku: string | null; levels: Array<{ locationId: string; quantity: number }> };
const initialState: TransferState = { message: "" };

export function TransferForm({ locations, products, selectedLocationId }: { locations: Location[]; products: Product[]; selectedLocationId: string }) {
  const [state, action, pending] = useActionState(createTransfer, initialState);
  const [source, setSource] = useState(selectedLocationId);
  const [destination, setDestination] = useState(locations.find((location) => location.id !== selectedLocationId)?.id ?? "");
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const available = useMemo(() => products.map((product) => ({ ...product, stock: product.levels.find((level) => level.locationId === source)?.quantity ?? 0 })).filter((product) => product.stock > 0), [products, source]);
  const items = available.filter((product) => (quantities[product.id] ?? 0) > 0).map((product) => ({ product_id: product.id, quantity: quantities[product.id] }));
  const change = (id: string, delta: number, max: number) => setQuantities((current) => ({ ...current, [id]: Math.max(0, Math.min(max, (current[id] ?? 0) + delta)) }));

  return <form action={action} className="space-y-6"><input type="hidden" name="items" value={JSON.stringify(items)} /><section className="grid gap-4 rounded-2xl border border-black/8 bg-white p-5 md:grid-cols-[1fr_auto_1fr]"><label><span className="mb-1.5 block text-sm font-semibold">Sucursal de origen</span><select name="sourceLocationId" value={source} onChange={(event) => { setSource(event.target.value); setQuantities({}); if (event.target.value === destination) setDestination(locations.find((location) => location.id !== event.target.value)?.id ?? ""); }} className="h-11 w-full rounded-xl border border-black/10 bg-white px-3">{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><ArrowRight className="hidden self-end text-[#789087] md:block md:mb-3" /><label><span className="mb-1.5 block text-sm font-semibold">Sucursal de destino</span><select name="destinationLocationId" value={destination} onChange={(event) => setDestination(event.target.value)} className="h-11 w-full rounded-xl border border-black/10 bg-white px-3">{locations.filter((location) => location.id !== source).map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label></section>
    <section className="overflow-hidden rounded-2xl border border-black/8 bg-white"><div className="border-b border-black/8 p-5"><h2 className="font-bold">Productos disponibles</h2><p className="mt-1 text-sm text-[#728078]">Selecciona las cantidades que saldrán de la sucursal de origen.</p></div><div className="divide-y divide-black/8">{!available.length && <div className="p-12 text-center text-sm text-[#728078]"><PackagePlus className="mx-auto mb-3" />No hay existencias disponibles en esta sucursal.</div>}{available.map((product) => <div key={product.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{product.name}</p><p className="text-xs text-[#75837b]">{product.sku || "Sin SKU"} · Disponible: {product.stock}</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => change(product.id, -1, product.stock)} className="grid size-9 place-items-center rounded-lg border border-black/10"><Minus size={15} /></button><input aria-label={`Cantidad de ${product.name}`} type="number" min="0" max={product.stock} step="0.001" value={quantities[product.id] ?? 0} onChange={(event) => setQuantities((current) => ({ ...current, [product.id]: Math.max(0, Math.min(product.stock, Number(event.target.value))) }))} className="h-9 w-24 rounded-lg border border-black/10 text-center font-bold" /><button type="button" onClick={() => change(product.id, 1, product.stock)} className="grid size-9 place-items-center rounded-lg border border-black/10"><Plus size={15} /></button></div></div>)}</div></section>
    <section className="grid gap-4 rounded-2xl border border-black/8 bg-white p-5 md:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold">Referencia</span><input name="reference" maxLength={100} className="h-11 w-full rounded-xl border border-black/10 px-3" placeholder="TR-001" /></label><label><span className="mb-1.5 block text-sm font-semibold">Notas</span><input name="notes" maxLength={500} className="h-11 w-full rounded-xl border border-black/10 px-3" /></label>{state.message && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 md:col-span-2">{state.message}</p>}<button disabled={pending || !items.length || !destination} className="h-12 rounded-xl bg-[#163f32] font-bold text-white disabled:opacity-50 md:col-span-2">{pending ? "Transfiriendo…" : `Transferir ${items.length} producto${items.length === 1 ? "" : "s"}`}</button></section>
  </form>;
}
