import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowLeftRight, Banknote, Ban, ClipboardList } from "lucide-react";
import { getOrganizationContext } from "@/lib/auth/organization";

const datePattern=/^\d{4}-\d{2}-\d{2}$/;
type Event={id:string;date:string;type:string;title:string;detail:string;amount?:number;link?:string;tone:"red"|"amber"|"green"|"blue"};
export default async function AuditPage({searchParams}:PageProps<"/auditoria">){const c=await getOrganizationContext();if(!["owner","admin","manager","viewer"].includes(c.role))return <main className="grid min-h-screen place-items-center bg-[#f4f5f1] text-red-700">Tu rol no permite consultar auditoría.</main>;const p=await searchParams,today=new Date().toLocaleDateString("en-CA",{timeZone:c.organization.timezone}),base=new Date(`${today}T12:00:00Z`);base.setUTCDate(base.getUTCDate()-30);const from=typeof p.from==="string"&&datePattern.test(p.from)?p.from:base.toISOString().slice(0,10),to=typeof p.to==="string"&&datePattern.test(p.to)?p.to:today,start=`${from}T00:00:00`,end=`${to}T23:59:59.999`;
 const[{data:saleVoids},{data:purchaseVoids},{data:sessions},{data:transfers},{data:cashMovements},{data:returns}]=await Promise.all([
 c.supabase.from("sale_voids").select("id,reason,voided_at,sale:sales(id,receipt_number,total)").eq("organization_id",c.organization.id).gte("voided_at",start).lte("voided_at",end),
 c.supabase.from("purchase_voids").select("id,reason,voided_at,purchase:purchases(id,reference,total)").eq("organization_id",c.organization.id).gte("voided_at",start).lte("voided_at",end),
 c.supabase.from("cash_register_sessions").select("id,difference,expected_amount,closing_amount,closed_at").eq("organization_id",c.organization.id).eq("location_id",c.location.id).eq("status","closed").gte("closed_at",start).lte("closed_at",end),
 c.supabase.from("inventory_transfers").select("id,reference,transferred_at,source:locations!inventory_transfers_source_location_id_fkey(name),destination:locations!inventory_transfers_destination_location_id_fkey(name),inventory_transfer_items(quantity)").eq("organization_id",c.organization.id).gte("transferred_at",start).lte("transferred_at",end),
 c.supabase.from("cash_register_movements").select("id,type,amount,reason,created_at,session:cash_register_sessions!inner(location_id)").eq("organization_id",c.organization.id).gte("created_at",start).lte("created_at",end),
 c.supabase.from("sale_returns").select("id,total,reason,created_at,sale:sales(receipt_number)").eq("organization_id",c.organization.id).gte("created_at",start).lte("created_at",end)
 ]);const one=<T,>(v:T|T[]|null)=>Array.isArray(v)?v[0]:v;const events:Event[]=[];
 (saleVoids??[]).forEach(v=>{const sale=one(v.sale as {id:string;receipt_number:string;total:number|string}|Array<{id:string;receipt_number:string;total:number|string}>|null);events.push({id:`sv-${v.id}`,date:v.voided_at,type:"Venta anulada",title:sale?.receipt_number||"Venta",detail:v.reason,amount:Number(sale?.total||0),link:sale?`/ventas/recibo/${sale.id}`:undefined,tone:"red"})});
 (purchaseVoids??[]).forEach(v=>{const purchase=one(v.purchase as {id:string;reference:string|null;total:number|string}|Array<{id:string;reference:string|null;total:number|string}>|null);events.push({id:`pv-${v.id}`,date:v.voided_at,type:"Compra anulada",title:purchase?.reference||"Recepción",detail:v.reason,amount:Number(purchase?.total||0),tone:"red"})});
 (sessions??[]).forEach(s=>events.push({id:`cs-${s.id}`,date:s.closed_at!,type:"Cierre de caja",title:`Diferencia ${Number(s.difference)>=0?"a favor":"faltante"}`,detail:`Esperado ${Number(s.expected_amount).toFixed(2)} · contado ${Number(s.closing_amount).toFixed(2)}`,amount:Number(s.difference),tone:Math.abs(Number(s.difference))>.009?"amber":"green"}));
 (transfers??[]).forEach(t=>{const source=one(t.source as {name?:string}|Array<{name?:string}>|null),destination=one(t.destination as {name?:string}|Array<{name?:string}>|null);events.push({id:`tr-${t.id}`,date:t.transferred_at,type:"Transferencia",title:t.reference||"Movimiento entre sucursales",detail:`${source?.name||"Origen"} → ${destination?.name||"Destino"} · ${(t.inventory_transfer_items as unknown[]??[]).length} productos`,link:"/transferencias",tone:"blue"})});
 (cashMovements??[]).forEach(m=>events.push({id:`cm-${m.id}`,date:m.created_at,type:m.type==="deposit"?"Ingreso de caja":"Retiro de caja",title:m.reason,detail:"Movimiento manual de efectivo",amount:(m.type==="deposit"?1:-1)*Number(m.amount),link:"/caja",tone:m.type==="deposit"?"green":"amber"}));
 (returns??[]).forEach(r=>{const sale=one(r.sale as {receipt_number?:string}|Array<{receipt_number?:string}>|null);events.push({id:`sr-${r.id}`,date:r.created_at,type:"Devolución",title:sale?.receipt_number||"Venta",detail:r.reason,amount:-Number(r.total),link:`/devoluciones/${r.id}`,tone:"amber"})});events.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());const currency=c.organization.currency_code==="GTQ"?"Q":c.organization.currency_code,anomalies=events.filter(e=>e.tone==="red"||e.tone==="amber").length;
 return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-6xl justify-between px-6 py-5"><div><p className="font-bold">{c.organization.name}</p><p className="text-xs text-white/60">Auditoría · toda la organización</p></div><Link href="/" className="flex items-center gap-2"><ArrowLeft size={16}/>Panel</Link></div></header><div className="mx-auto max-w-6xl space-y-6 px-6 py-9"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#517064]">Control interno</p><h1 className="mt-2 text-4xl font-bold">Centro de auditoría</h1></div><form className="flex items-end gap-2 rounded-xl bg-white p-3"><DateField label="Desde" name="from" value={from}/><DateField label="Hasta" name="to" value={to}/><button className="h-10 rounded-lg bg-[#163f32] px-4 text-sm font-bold text-white">Aplicar</button></form></div><section className="grid gap-4 sm:grid-cols-3"><Metric label="Eventos" value={events.length} icon={ClipboardList}/><Metric label="Requieren revisión" value={anomalies} icon={AlertTriangle}/><Metric label="Transferencias" value={transfers?.length??0} icon={ArrowLeftRight}/></section><section className="rounded-2xl border border-black/8 bg-white"><h2 className="border-b p-5 font-bold">Línea de tiempo</h2>{!events.length&&<p className="p-12 text-center text-sm text-[#728078]">No hay eventos en este período.</p>}<div className="divide-y">{events.map(e=><article key={e.id} className="grid gap-3 p-4 sm:grid-cols-[42px_1fr_auto] sm:items-center"><span className={`grid size-10 place-items-center rounded-xl ${e.tone==="red"?"bg-red-50 text-red-700":e.tone==="amber"?"bg-amber-50 text-amber-700":e.tone==="green"?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{e.type.includes("anulada")?<Ban size={18}/>:e.type.includes("caja")?<Banknote size={18}/>:<ArrowLeftRight size={18}/>}</span><div><p className="text-xs font-bold uppercase tracking-wider text-[#75837b]">{e.type}</p><p className="font-bold">{e.title}</p><p className="text-sm text-[#68766f]">{e.detail}</p><p className="mt-1 text-xs text-[#89938e]">{new Intl.DateTimeFormat("es-GT",{dateStyle:"medium",timeStyle:"short",timeZone:c.organization.timezone}).format(new Date(e.date))}</p></div><div className="text-right">{e.amount!==undefined&&<strong className={e.amount<0?"text-red-700":""}>{currency} {e.amount.toFixed(2)}</strong>}{e.link&&<Link href={e.link} className="mt-1 block text-xs font-bold text-[#285645] hover:underline">Ver detalle</Link>}</div></article>)}</div></section></div></main>}
function DateField({label,name,value}:{label:string;name:string;value:string}){return <label><span className="mb-1 block text-xs font-semibold">{label}</span><input type="date" name={name} defaultValue={value} className="h-10 rounded-lg border px-2 text-sm"/></label>};function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof ClipboardList}){return <article className="rounded-2xl bg-white p-5"><div className="flex justify-between text-sm"><span>{label}</span><Icon size={18}/></div><p className="mt-5 text-2xl font-bold">{value}</p></article>}
