import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleDollarSign, CreditCard, ReceiptText, Users } from "lucide-react";
import { canManageCustomers, canViewReports, getOrganizationContext } from "@/lib/auth/organization";
import { recordPayment } from "./actions";

const methodLabels: Record<string,string> = { cash: "Efectivo", card: "Tarjeta", transfer: "Transferencia", other: "Otro" };
const input = "h-11 w-full rounded-xl border border-black/10 bg-white px-3 outline-none focus:border-[#3e735e]";

export default async function CreditsPage({ searchParams }: PageProps<"/creditos">) {
  const context = await getOrganizationContext();
  const params = await searchParams;
  const canManage = canManageCustomers(context.role);
  const canRead = canManage || canViewReports(context.role);
  if (!canRead) return <main className="grid min-h-screen place-items-center bg-[#f4f5f1] text-red-700">Tu rol no permite consultar cuentas por cobrar.</main>;
  const [{ data: customers }, { data: movements }] = await Promise.all([
    context.supabase.from("customers").select("id, first_name, last_name, company_name, phone").eq("organization_id", context.organization.id).eq("active", true).order("first_name"),
    context.supabase.from("customer_account_movements").select("id, customer_id, sale_id, type, amount, payment_method, reference, notes, created_at").eq("organization_id", context.organization.id).order("created_at", { ascending: false }).limit(1000),
  ]);
  const balances = new Map<string, number>();
  (movements ?? []).forEach((movement) => balances.set(movement.customer_id, (balances.get(movement.customer_id) ?? 0) + (movement.type === "charge" ? Number(movement.amount) : -Number(movement.amount))));
  const debtors = (customers ?? []).map((customer) => ({ ...customer, balance: balances.get(customer.id) ?? 0, name: customer.company_name || `${customer.first_name} ${customer.last_name}`.trim() })).filter((customer) => customer.balance > 0.005).sort((a,b) => b.balance-a.balance);
  const totalDue = debtors.reduce((sum, customer) => sum + customer.balance, 0);
  const currency = context.organization.currency_code === "GTQ" ? "Q" : context.organization.currency_code;

  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><div><p className="text-lg font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Créditos · {context.location.name}</p></div><Link href="/" className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold"><ArrowLeft size={16} /> Panel</Link></div></header><div className="mx-auto max-w-7xl space-y-6 px-6 py-9 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#517064]">Clientes</p><h1 className="mt-2 text-4xl font-bold tracking-[-0.04em]">Cuentas por cobrar</h1></div>{params.paid && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18} /> Abono registrado correctamente.</p>}{params.error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">No fue posible registrar el abono. Verifica que no supere el saldo pendiente.</p>}
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Saldo total" value={`${currency} ${totalDue.toFixed(2)}`} icon={CircleDollarSign} /><Metric label="Clientes con saldo" value={String(debtors.length)} icon={Users} /><Metric label="Movimientos" value={String(movements?.length ?? 0)} icon={ReceiptText} /></section>
    <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-black/8 bg-white"><h2 className="border-b border-black/8 p-5 font-bold">Saldos pendientes</h2><div className="divide-y divide-black/8">{!debtors.length && <p className="p-10 text-center text-sm text-[#728078]">No hay saldos pendientes.</p>}{debtors.map((customer) => <Link href={`/creditos/${customer.id}`} key={customer.id} className="flex items-center justify-between gap-4 p-4 hover:bg-[#f6f7f4]"><div><p className="font-bold">{customer.name}</p><p className="mt-1 text-xs text-[#75837b]">{customer.phone || "Sin teléfono"} · Ver estado de cuenta</p></div><strong className="text-lg text-amber-700">{currency} {customer.balance.toFixed(2)}</strong></Link>)}</div></section>{canManage && <form action={recordPayment} className="h-fit rounded-2xl border border-black/8 bg-white p-5"><h2 className="flex items-center gap-2 font-bold"><CreditCard size={18} /> Registrar abono</h2><div className="mt-5 space-y-3"><label><span className="mb-1 block text-xs font-semibold">Cliente</span><select name="customerId" required className={input}><option value="">Seleccionar</option>{debtors.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} · {currency} {customer.balance.toFixed(2)}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold">Monto</span><input name="amount" type="number" min="0.01" step="0.01" required className={input} /></label><label><span className="mb-1 block text-xs font-semibold">Método</span><select name="method" className={input}><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label><label><span className="mb-1 block text-xs font-semibold">Referencia</span><input name="reference" maxLength={100} className={input} /></label><label><span className="mb-1 block text-xs font-semibold">Notas</span><input name="notes" maxLength={300} className={input} /></label><button disabled={!debtors.length} className="h-11 w-full rounded-xl bg-[#163f32] font-bold text-white disabled:opacity-50">Guardar abono</button></div></form>}</div>
    <section className="rounded-2xl border border-black/8 bg-white"><h2 className="border-b border-black/8 p-5 font-bold">Historial de cuenta</h2><div className="divide-y divide-black/8">{!movements?.length && <p className="p-10 text-center text-sm text-[#728078]">No hay movimientos.</p>}{movements?.slice(0,100).map((movement) => { const customer = customers?.find((item) => item.id === movement.customer_id); const name = customer?.company_name || `${customer?.first_name ?? ""} ${customer?.last_name ?? ""}`.trim() || "Cliente"; const positive = movement.type === "charge"; return <article key={movement.id} className="grid gap-2 p-4 text-sm md:grid-cols-[1fr_1fr_auto]"><div><p className="font-bold">{name}</p><p className="text-xs text-[#75837b]">{movement.type === "charge" ? "Venta al crédito" : movement.type === "payment" ? `Abono · ${methodLabels[movement.payment_method ?? ""] ?? "Otro"}` : "Anulación"}</p></div><div>{movement.sale_id ? <Link href={`/ventas/recibo/${movement.sale_id}`} className="font-mono font-semibold text-[#285645] hover:underline">Ver recibo</Link> : movement.reference || movement.notes || "—"}<p className="mt-1 text-xs text-[#75837b]">{new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Guatemala" }).format(new Date(movement.created_at))}</p></div><strong className={positive ? "text-amber-700" : "text-emerald-700"}>{positive ? "+" : "−"}{currency} {Number(movement.amount).toFixed(2)}</strong></article>; })}</div></section></div></main>;
}

function Metric({ label, value, icon: Icon }: { label:string; value:string; icon: typeof CircleDollarSign }) { return <article className="rounded-2xl border border-black/8 bg-white p-5"><div className="flex justify-between text-sm text-[#617069]"><span>{label}</span><Icon size={18} /></div><p className="mt-5 text-2xl font-bold">{value}</p></article>; }
