import Link from "next/link";
import { ArrowLeft, FilePlus2 } from "lucide-react";
import { canManageCustomers, getOrganizationContext } from "@/lib/auth/organization";
import { QuoteBuilder } from "./quote-builder";

export default async function QuotesPage(){
  const context=await getOrganizationContext(),allowed=canManageCustomers(context.role);
  const[{data:products},{data:customers},{data:quotes}]=await Promise.all([
    context.supabase.from("products").select("id,name,sku,price,tax_rate,product_variants(id,name,sku,price,active)").eq("organization_id",context.organization.id).eq("active",true).order("name"),
    context.supabase.from("customers").select("id,first_name,last_name,company_name").eq("organization_id",context.organization.id).eq("active",true).order("first_name"),
    context.supabase.from("quotes").select("id,quote_number,status,total,valid_until,created_at,customer:customers(first_name,last_name,company_name)").eq("organization_id",context.organization.id).order("created_at",{ascending:false}).limit(50),
  ]);
  const currency=context.organization.currency_code==="GTQ"?"Q":context.organization.currency_code;
  const catalog=(products??[]).flatMap(product=>[{id:product.id,variantId:null as string|null,name:product.name,sku:product.sku,price:Number(product.price),taxRate:Number(product.tax_rate)},...(product.product_variants??[]).filter(variant=>variant.active).map(variant=>({id:product.id,variantId:variant.id,name:`${product.name} · ${variant.name}`,sku:variant.sku||product.sku,price:Number(variant.price??product.price),taxRate:Number(product.tax_rate)}))]);
  const normalizedCustomers=(customers??[]).map(customer=>({id:customer.id,name:customer.company_name||`${customer.first_name} ${customer.last_name}`.trim()}));
  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><div><p className="text-lg font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Cotizaciones · {context.location.name}</p></div><Link href="/" className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold"><ArrowLeft size={16}/>Panel</Link></div></header><div className="mx-auto max-w-7xl space-y-7 px-6 py-9 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#517064]">Ventas</p><h1 className="mt-2 text-4xl font-bold">Cotizaciones</h1></div>{allowed?<QuoteBuilder products={catalog} customers={normalizedCustomers} currency={currency} today={new Date().toLocaleDateString("en-CA",{timeZone:context.organization.timezone})}/>:<p className="rounded-2xl bg-white p-8 text-red-700">Tu rol no permite crear cotizaciones.</p>}<section className="rounded-2xl border border-black/8 bg-white"><h2 className="flex items-center gap-2 border-b border-black/8 p-5 font-bold"><FilePlus2 size={18}/>Cotizaciones recientes</h2><div className="divide-y divide-black/8">{!quotes?.length&&<p className="p-10 text-center text-sm text-[#728078]">No hay cotizaciones.</p>}{quotes?.map(quote=>{const value=quote.customer as {first_name?:string;last_name?:string;company_name?:string|null}|Array<{first_name?:string;last_name?:string;company_name?:string|null}>|null,customer=Array.isArray(value)?value[0]:value;return <Link href={`/cotizaciones/${quote.id}`} key={quote.id} className="grid gap-2 p-4 text-sm hover:bg-[#f6f7f4] sm:grid-cols-[1fr_1fr_auto]"><div><p className="font-mono font-bold text-[#285645]">{quote.quote_number}</p><p className="text-xs text-[#75837b]">{customer?customer.company_name||`${customer.first_name??""} ${customer.last_name??""}`.trim():"Consumidor final"}</p></div><p>{quote.status==="draft"?"Vigente":quote.status==="converted"?"Convertida":"Cancelada"}{quote.valid_until?` · hasta ${quote.valid_until}`:""}</p><strong>{currency} {Number(quote.total).toFixed(2)}</strong></Link>})}</div></section></div></main>;
}
