"use client";
import { useActionState, useState } from "react";
import { Minus, Plus, Trash2 } from "lucide-react";
import { createQuote, type QuoteState } from "./actions";

type Product={id:string;variantId:string|null;name:string;sku:string|null;price:number;taxRate:number};
type Customer={id:string;name:string};
type Line=Product&{quantity:number};
const key=(value:Pick<Product,"id"|"variantId">)=>`${value.id}:${value.variantId??"base"}`;

export function QuoteBuilder({products,customers,currency,today}:{products:Product[];customers:Customer[];currency:string;today:string}){
  const[state,action,pending]=useActionState(createQuote,{message:""} as QuoteState);
  const[lines,setLines]=useState<Line[]>([]);
  const add=(selected:string)=>{const product=products.find(item=>key(item)===selected);if(!product)return;setLines(current=>current.some(item=>key(item)===selected)?current.map(item=>key(item)===selected?{...item,quantity:item.quantity+1}:item):[...current,{...product,quantity:1}])};
  const change=(selected:string,delta:number)=>setLines(current=>current.map(item=>key(item)===selected?{...item,quantity:Math.max(1,item.quantity+delta)}:item));
  const subtotal=lines.reduce((sum,item)=>sum+item.price*item.quantity,0),tax=lines.reduce((sum,item)=>sum+item.price*item.quantity*item.taxRate,0);
  return <form action={action} className="grid gap-6 lg:grid-cols-[1fr_360px]">
    <input type="hidden" name="items" value={JSON.stringify(lines.map(item=>({product_id:item.id,variant_id:item.variantId,quantity:item.quantity})))} />
    <section className="rounded-2xl border border-black/8 bg-white p-5"><h2 className="font-bold">Productos y variantes</h2><select defaultValue="" onChange={event=>{add(event.target.value);event.target.value=""}} className="mt-4 h-11 w-full rounded-xl border border-black/10 bg-white px-3"><option value="">Agregar producto o variante…</option>{products.map(product=><option key={key(product)} value={key(product)}>{product.name}{product.sku?` · ${product.sku}`:""} · {currency} {product.price.toFixed(2)}</option>)}</select><div className="mt-5 divide-y divide-black/8">{!lines.length&&<p className="py-10 text-center text-sm text-[#728078]">Agrega productos a la cotización.</p>}{lines.map(line=>{const lineKey=key(line);return <div key={lineKey} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="font-semibold">{line.name}</p><p className="text-xs text-[#75837b]">{line.sku||"Sin SKU"} · {currency} {line.price.toFixed(2)}</p></div><button type="button" onClick={()=>change(lineKey,-1)} className="grid size-8 place-items-center rounded-lg border"><Minus size={14}/></button><strong>{line.quantity}</strong><button type="button" onClick={()=>change(lineKey,1)} className="grid size-8 place-items-center rounded-lg border"><Plus size={14}/></button><button type="button" onClick={()=>setLines(current=>current.filter(item=>key(item)!==lineKey))} className="text-red-700"><Trash2 size={16}/></button></div>})}</div></section>
    <aside className="h-fit rounded-2xl border border-black/8 bg-white p-5"><h2 className="font-bold">Información</h2><label className="mt-4 block"><span className="mb-1 block text-xs font-semibold">Cliente</span><select name="customerId" className="h-11 w-full rounded-xl border border-black/10 bg-white px-3"><option value="">Consumidor final</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label className="mt-3 block"><span className="mb-1 block text-xs font-semibold">Válida hasta</span><input name="validUntil" type="date" min={today} className="h-11 w-full rounded-xl border border-black/10 px-3" /></label><label className="mt-3 block"><span className="mb-1 block text-xs font-semibold">Notas</span><textarea name="notes" maxLength={500} className="min-h-20 w-full rounded-xl border border-black/10 p-3" /></label><div className="mt-5 space-y-2 border-t border-dashed pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{currency} {subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Impuestos</span><span>{currency} {tax.toFixed(2)}</span></div><div className="flex justify-between text-xl font-bold"><span>Total</span><span>{currency} {(subtotal+tax).toFixed(2)}</span></div></div>{state.message&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<button disabled={pending||!lines.length} className="mt-5 h-11 w-full rounded-xl bg-[#163f32] font-bold text-white disabled:opacity-50">{pending?"Guardando…":"Crear cotización"}</button></aside>
  </form>;
}
