"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { canManageInventory, getOrganizationContext } from "@/lib/auth/organization";
const schema=z.object({kind:z.enum(["category","manufacturer","tag"]),id:z.preprocess(v=>v??"",z.string().transform(v=>v||null).pipe(z.uuid().nullable())),name:z.string().trim().min(2).max(160),description:z.string().trim().max(500).transform(v=>v||null),website:z.string().trim().max(300).transform(v=>v||null),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/)});
export async function saveCatalogValue(formData:FormData){const p=schema.safeParse({kind:formData.get("kind"),id:formData.get("id"),name:formData.get("name"),description:formData.get("description")??"",website:formData.get("website")??"",color:formData.get("color")??"#285645"});if(!p.success)redirect("/inventario/catalogos?error=invalid");const c=await getOrganizationContext();if(!canManageInventory(c.role))redirect("/inventario/catalogos?error=permissions");const table=p.data.kind==="category"?"categories":p.data.kind==="manufacturer"?"manufacturers":"tags",values=p.data.kind==="category"?{name:p.data.name}:p.data.kind==="manufacturer"?{name:p.data.name,description:p.data.description,website:p.data.website,active:true}:{name:p.data.name,color:p.data.color,active:true};const op=p.data.id?c.supabase.from(table).update(values).eq("id",p.data.id).eq("organization_id",c.organization.id).select("id").maybeSingle():c.supabase.from(table).insert({organization_id:c.organization.id,...values}).select("id").single();const{data,error}=await op;if(error||!data)redirect(`/inventario/catalogos?error=${error?.code==="23505"?"duplicate":"save"}`);revalidatePath("/inventario/catalogos");revalidatePath("/inventario");redirect(`/inventario/catalogos?saved=${p.data.kind}`)}
export async function deactivateCatalogValue(formData:FormData){const p=z.object({kind:z.enum(["manufacturer","tag"]),id:z.uuid()}).safeParse({kind:formData.get("kind"),id:formData.get("id")});if(!p.success)redirect("/inventario/catalogos?error=invalid");const c=await getOrganizationContext();if(!canManageInventory(c.role))redirect("/inventario/catalogos?error=permissions");const table=p.data.kind==="manufacturer"?"manufacturers":"tags";const{data,error}=await c.supabase.from(table).update({active:false}).eq("id",p.data.id).eq("organization_id",c.organization.id).eq("active",true).select("id").maybeSingle();if(error||!data)redirect("/inventario/catalogos?error=deactivate");revalidatePath("/inventario/catalogos");revalidatePath("/inventario");redirect(`/inventario/catalogos?deactivated=${p.data.kind}`)}

const attributeSchema=z.object({id:z.preprocess(v=>v??"",z.string().transform(v=>v||null).pipe(z.uuid().nullable())),name:z.string().trim().min(2).max(100)});
export async function saveAttribute(formData:FormData){const p=attributeSchema.safeParse({id:formData.get("id"),name:formData.get("name")});if(!p.success)redirect("/inventario/catalogos?error=invalid");const c=await getOrganizationContext();if(!canManageInventory(c.role))redirect("/inventario/catalogos?error=permissions");const values={name:p.data.name,active:true};const op=p.data.id?c.supabase.from("product_attributes").update(values).eq("id",p.data.id).eq("organization_id",c.organization.id).select("id").maybeSingle():c.supabase.from("product_attributes").insert({organization_id:c.organization.id,...values}).select("id").single();const{data,error}=await op;if(error||!data)redirect(`/inventario/catalogos?error=${error?.code==="23505"?"duplicate":"save"}`);revalidatePath("/inventario/catalogos");redirect("/inventario/catalogos?saved=attribute#attributes")}

export async function saveAttributeValue(formData:FormData){const p=z.object({attributeId:z.uuid(),value:z.string().trim().min(1).max(100)}).safeParse({attributeId:formData.get("attributeId"),value:formData.get("value")});if(!p.success)redirect("/inventario/catalogos?error=invalid");const c=await getOrganizationContext();if(!canManageInventory(c.role))redirect("/inventario/catalogos?error=permissions");const{data:attribute}=await c.supabase.from("product_attributes").select("id").eq("id",p.data.attributeId).eq("organization_id",c.organization.id).eq("active",true).maybeSingle();if(!attribute)redirect("/inventario/catalogos?error=invalid");const{error}=await c.supabase.from("product_attribute_values").insert({organization_id:c.organization.id,attribute_id:p.data.attributeId,value:p.data.value});if(error)redirect(`/inventario/catalogos?error=${error.code==="23505"?"duplicate":"save"}`);revalidatePath("/inventario/catalogos");redirect("/inventario/catalogos?saved=value#attributes")}

export async function deactivateAttributeItem(formData:FormData){const p=z.object({kind:z.enum(["attribute","value"]),id:z.uuid()}).safeParse({kind:formData.get("kind"),id:formData.get("id")});if(!p.success)redirect("/inventario/catalogos?error=invalid");const c=await getOrganizationContext();if(!canManageInventory(c.role))redirect("/inventario/catalogos?error=permissions");const table=p.data.kind==="attribute"?"product_attributes":"product_attribute_values";const{data,error}=await c.supabase.from(table).update({active:false}).eq("id",p.data.id).eq("organization_id",c.organization.id).eq("active",true).select("id").maybeSingle();if(error||!data)redirect("/inventario/catalogos?error=deactivate");revalidatePath("/inventario/catalogos");redirect("/inventario/catalogos?deactivated=attribute#attributes")}
