import type { NextRequest } from "next/server";
import { getOrganizationContext } from "@/lib/auth/organization";

const allowedTypes=["sales","inventory","customers","receivables","payables"] as const;
type ExportType=typeof allowedTypes[number];
const escape=(value:unknown)=>{const text=value==null?"":String(value);return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text};
const csv=(headers:string[],rows:unknown[][])=>"\ufeff"+[headers,...rows].map(row=>row.map(escape).join(",")).join("\r\n");

export async function GET(request:NextRequest,{params}:RouteContext<"/api/export/[type]">){const{type}=await params;if(!allowedTypes.includes(type as ExportType))return new Response("Tipo de exportación inválido",{status:404});const c=await getOrganizationContext();const exportType=type as ExportType;if(exportType==="sales"&&!(["owner","admin","manager","viewer"].includes(c.role)))return new Response("Sin permiso",{status:403});if(exportType==="payables"&&!(["owner","admin","manager","inventory","viewer"].includes(c.role)))return new Response("Sin permiso",{status:403});
 let body="";const from=request.nextUrl.searchParams.get("from"),to=request.nextUrl.searchParams.get("to");
 if(exportType==="sales"){let q=c.supabase.from("sales").select("receipt_number,status,subtotal,discount_total,tax_total,total,completed_at,customer:customers(first_name,last_name,company_name,tax_id),payments(method,amount)").eq("organization_id",c.organization.id).eq("location_id",c.location.id).order("completed_at",{ascending:false}).limit(5000);if(from)q=q.gte("completed_at",`${from}T00:00:00`);if(to)q=q.lte("completed_at",`${to}T23:59:59.999`);const{data}=await q;body=csv(["Recibo","Estado","Fecha","Cliente","NIT","Subtotal","Descuento","Impuestos","Total","Métodos de pago"],(data??[]).map(s=>{const cv=s.customer as {first_name?:string;last_name?:string;company_name?:string|null;tax_id?:string|null}|Array<{first_name?:string;last_name?:string;company_name?:string|null;tax_id?:string|null}>|null,customer=Array.isArray(cv)?cv[0]:cv;return[s.receipt_number,s.status,s.completed_at,customer?customer.company_name||`${customer.first_name??""} ${customer.last_name??""}`.trim():"Consumidor final",customer?.tax_id,Number(s.subtotal).toFixed(2),Number(s.discount_total).toFixed(2),Number(s.tax_total).toFixed(2),Number(s.total).toFixed(2),(s.payments as Array<{method:string}>??[]).map(p=>p.method).join(" + ")] }));}
 if(exportType==="inventory"){const{data}=await c.supabase.from("products").select("name,sku,barcode,cost,price,active,category:categories(name),inventory_levels(quantity,reorder_point,location_id)").eq("organization_id",c.organization.id).order("name");body=csv(["Producto","SKU","Código de barras","Categoría","Costo","Precio","Existencia","Punto de reorden","Estado"],(data??[]).map(p=>{const cv=p.category as {name?:string}|Array<{name?:string}>|null,category=Array.isArray(cv)?cv[0]:cv,level=(p.inventory_levels as Array<{location_id:string;quantity:string|number;reorder_point:string|number}>??[]).find(x=>x.location_id===c.location.id);return[p.name,p.sku,p.barcode,category?.name,Number(p.cost).toFixed(2),Number(p.price).toFixed(2),Number(level?.quantity??0),Number(level?.reorder_point??0),p.active?"Activo":"Inactivo"]}));}
 if(exportType==="customers"){const{data}=await c.supabase.from("customers").select("first_name,last_name,company_name,email,phone,tax_id,address,active,created_at").eq("organization_id",c.organization.id).order("first_name");body=csv(["Nombre","Apellido","Empresa","Correo","Teléfono","NIT","Dirección","Estado","Creado"],(data??[]).map(x=>[x.first_name,x.last_name,x.company_name,x.email,x.phone,x.tax_id,x.address,x.active?"Activo":"Inactivo",x.created_at]));}
 if(exportType==="receivables"){const[{data:customers},{data:movements}]=await Promise.all([c.supabase.from("customers").select("id,first_name,last_name,company_name,tax_id,phone").eq("organization_id",c.organization.id),c.supabase.from("customer_account_movements").select("customer_id,type,amount").eq("organization_id",c.organization.id)]);const balances=new Map<string,number>();(movements??[]).forEach(x=>balances.set(x.customer_id,(balances.get(x.customer_id)??0)+(x.type==="charge"?Number(x.amount):-Number(x.amount))));body=csv(["Cliente","NIT","Teléfono","Saldo"],(customers??[]).map(x=>[x.company_name||`${x.first_name} ${x.last_name}`.trim(),x.tax_id,x.phone,(balances.get(x.id)??0).toFixed(2)]).filter(row=>Number(row[3])>0));}
 if(exportType==="payables"){const[{data:suppliers},{data:movements}]=await Promise.all([c.supabase.from("suppliers").select("id,name,tax_id,phone").eq("organization_id",c.organization.id),c.supabase.from("supplier_account_movements").select("supplier_id,type,amount").eq("organization_id",c.organization.id)]);const balances=new Map<string,number>();(movements??[]).forEach(x=>balances.set(x.supplier_id,(balances.get(x.supplier_id)??0)+(x.type==="charge"?Number(x.amount):-Number(x.amount))));body=csv(["Proveedor","NIT","Teléfono","Saldo"],(suppliers??[]).map(x=>[x.name,x.tax_id,x.phone,(balances.get(x.id)??0).toFixed(2)]).filter(row=>Number(row[3])>0));}
 const stamp=new Date().toISOString().slice(0,10);return new Response(body,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="stm-${exportType}-${stamp}.csv"`,"Cache-Control":"private, no-store"}})}
