import type { NextRequest } from "next/server";
import { getOrganizationContext } from "@/lib/auth/organization";

const allowedTypes=["sales","returns","purchases","purchase-returns","suppliers","inventory","customers","receivables","payables"] as const;
type ExportType=typeof allowedTypes[number];
const escape=(value:unknown)=>{const text=value==null?"":String(value);return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text};
const csv=(headers:string[],rows:unknown[][])=>"\ufeff"+[headers,...rows].map(row=>row.map(escape).join(",")).join("\r\n");

export async function GET(request:NextRequest,{params}:RouteContext<"/api/export/[type]">){const{type}=await params;if(!allowedTypes.includes(type as ExportType))return new Response("Tipo de exportación inválido",{status:404});const c=await getOrganizationContext();const exportType=type as ExportType;if(["sales","returns"].includes(exportType)&&!(["owner","admin","manager","viewer"].includes(c.role)))return new Response("Sin permiso",{status:403});if(["purchases","purchase-returns","suppliers","payables"].includes(exportType)&&!(["owner","admin","manager","inventory","viewer"].includes(c.role)))return new Response("Sin permiso",{status:403});
 let body="";const from=request.nextUrl.searchParams.get("from"),to=request.nextUrl.searchParams.get("to");
 if(exportType==="sales"){let q=c.supabase.from("sales").select("receipt_number,status,subtotal,discount_total,tax_total,total,completed_at,customer:customers(first_name,last_name,company_name,tax_id),payments(method,amount)").eq("organization_id",c.organization.id).eq("location_id",c.location.id).order("completed_at",{ascending:false}).limit(5000);if(from)q=q.gte("completed_at",`${from}T00:00:00`);if(to)q=q.lte("completed_at",`${to}T23:59:59.999`);const{data}=await q;body=csv(["Recibo","Estado","Fecha","Cliente","NIT","Subtotal","Descuento","Impuestos","Total","Métodos de pago"],(data??[]).map(s=>{const cv=s.customer as {first_name?:string;last_name?:string;company_name?:string|null;tax_id?:string|null}|Array<{first_name?:string;last_name?:string;company_name?:string|null;tax_id?:string|null}>|null,customer=Array.isArray(cv)?cv[0]:cv;return[s.receipt_number,s.status,s.completed_at,customer?customer.company_name||`${customer.first_name??""} ${customer.last_name??""}`.trim():"Consumidor final",customer?.tax_id,Number(s.subtotal).toFixed(2),Number(s.discount_total).toFixed(2),Number(s.tax_total).toFixed(2),Number(s.total).toFixed(2),(s.payments as Array<{method:string}>??[]).map(p=>p.method).join(" + ")] }));}
 if(exportType==="returns"){let q=c.supabase.from("sale_returns").select("id,created_at,refund_method,total,reason,created_by,sale:sales(receipt_number),sale_return_items(quantity)").eq("organization_id",c.organization.id).eq("location_id",c.location.id).order("created_at",{ascending:false}).limit(5000);if(from)q=q.gte("created_at",`${from}T00:00:00`);if(to)q=q.lte("created_at",`${to}T23:59:59.999`);const{data}=await q;body=csv(["Devolución","Recibo original","Fecha","Método","Unidades","Motivo","Responsable","Total"],(data??[]).map(r=>{const sv=r.sale as {receipt_number?:string}|Array<{receipt_number?:string}>|null,sale=Array.isArray(sv)?sv[0]:sv;return[`DEV-${r.id.slice(0,8).toUpperCase()}`,sale?.receipt_number,r.created_at,r.refund_method,(r.sale_return_items as Array<{quantity:string|number}>??[]).reduce((sum,x)=>sum+Number(x.quantity),0),r.reason,r.created_by,Number(r.total).toFixed(2)]}));}
 if(exportType==="purchases"){let q=c.supabase.from("purchases").select("reference,status,payment_terms,subtotal,tax_total,total,received_at,supplier:suppliers(name,tax_id),purchase_items(quantity)").eq("organization_id",c.organization.id).eq("location_id",c.location.id).order("received_at",{ascending:false}).limit(5000);if(from)q=q.gte("received_at",`${from}T00:00:00`);if(to)q=q.lte("received_at",`${to}T23:59:59.999`);const{data}=await q;body=csv(["Referencia","Estado","Fecha","Proveedor","NIT","Condición","Unidades","Subtotal","Impuestos","Total"],(data??[]).map(p=>{const sv=p.supplier as {name?:string;tax_id?:string|null}|Array<{name?:string;tax_id?:string|null}>|null,supplier=Array.isArray(sv)?sv[0]:sv;return[p.reference,p.status,p.received_at,supplier?.name,supplier?.tax_id,p.payment_terms,(p.purchase_items as Array<{quantity:string|number}>??[]).reduce((sum,x)=>sum+Number(x.quantity),0),Number(p.subtotal).toFixed(2),Number(p.tax_total).toFixed(2),Number(p.total).toFixed(2)]}));}
 if(exportType==="purchase-returns"){const{data}=await c.supabase.from("purchase_returns").select("id,created_at,resolution,total,reason,created_by,purchase:purchases(reference),supplier:suppliers(name),purchase_return_items(quantity)").eq("organization_id",c.organization.id).eq("location_id",c.location.id).order("created_at",{ascending:false}).limit(5000);body=csv(["Devolución","Compra original","Fecha","Proveedor","Resolución","Unidades","Motivo","Responsable","Total"],(data??[]).map(r=>{const pv=r.purchase as {reference?:string}|Array<{reference?:string}>|null,p=Array.isArray(pv)?pv[0]:pv,sv=r.supplier as {name?:string}|Array<{name?:string}>|null,s=Array.isArray(sv)?sv[0]:sv;return[`DCP-${r.id.slice(0,8).toUpperCase()}`,p?.reference,r.created_at,s?.name,r.resolution,(r.purchase_return_items as Array<{quantity:string|number}>??[]).reduce((sum,x)=>sum+Number(x.quantity),0),r.reason,r.created_by,Number(r.total).toFixed(2)]}));}
 if(exportType==="suppliers"){const{data}=await c.supabase.from("suppliers").select("name,contact_name,email,phone,tax_id,address,credit_limit,active,created_at").eq("organization_id",c.organization.id).order("name");body=csv(["Proveedor","Contacto","Correo","Teléfono","NIT","Dirección","Límite de crédito","Estado","Creado"],(data??[]).map(s=>[s.name,s.contact_name,s.email,s.phone,s.tax_id,s.address,s.credit_limit,s.active?"Activo":"Inactivo",s.created_at]));}
 if(exportType==="inventory"){const{data}=await c.supabase.from("products").select("name,sku,barcode,cost,price,active,category:categories(name),inventory_levels(quantity,reorder_point,location_id),product_variants(name,sku,barcode,cost,price,active,variant_inventory_levels(quantity,reorder_point,location_id))").eq("organization_id",c.organization.id).order("name");body=csv(["Producto / variante","Tipo","SKU","Código de barras","Categoría","Costo","Precio","Existencia","Punto de reorden","Estado"],(data??[]).flatMap(p=>{const cv=p.category as {name?:string}|Array<{name?:string}>|null,category=Array.isArray(cv)?cv[0]:cv,level=(p.inventory_levels as Array<{location_id:string;quantity:string|number;reorder_point:string|number}>??[]).find(x=>x.location_id===c.location.id),base=[p.name,"Producto",p.sku,p.barcode,category?.name,Number(p.cost).toFixed(2),Number(p.price).toFixed(2),Number(level?.quantity??0),Number(level?.reorder_point??0),p.active?"Activo":"Inactivo"];const variants=(p.product_variants as Array<{name:string;sku:string|null;barcode:string|null;cost:string|number|null;price:string|number|null;active:boolean;variant_inventory_levels:Array<{location_id:string;quantity:string|number;reorder_point:string|number}>}>??[]).map(v=>{const variantLevel=(v.variant_inventory_levels??[]).find(x=>x.location_id===c.location.id);return[`${p.name} · ${v.name}`,"Variante",v.sku||p.sku,v.barcode||p.barcode,category?.name,Number(v.cost??p.cost).toFixed(2),Number(v.price??p.price).toFixed(2),Number(variantLevel?.quantity??0),Number(variantLevel?.reorder_point??0),p.active&&v.active?"Activo":"Inactivo"]});return[base,...variants]}));}
 if(exportType==="customers"){const{data}=await c.supabase.from("customers").select("first_name,last_name,company_name,email,phone,tax_id,address,active,created_at").eq("organization_id",c.organization.id).order("first_name");body=csv(["Nombre","Apellido","Empresa","Correo","Teléfono","NIT","Dirección","Estado","Creado"],(data??[]).map(x=>[x.first_name,x.last_name,x.company_name,x.email,x.phone,x.tax_id,x.address,x.active?"Activo":"Inactivo",x.created_at]));}
 if(exportType==="receivables"){const[{data:customers},{data:movements}]=await Promise.all([c.supabase.from("customers").select("id,first_name,last_name,company_name,tax_id,phone").eq("organization_id",c.organization.id),c.supabase.from("customer_account_movements").select("customer_id,type,amount").eq("organization_id",c.organization.id)]);const balances=new Map<string,number>();(movements??[]).forEach(x=>balances.set(x.customer_id,(balances.get(x.customer_id)??0)+(x.type==="charge"?Number(x.amount):-Number(x.amount))));body=csv(["Cliente","NIT","Teléfono","Saldo"],(customers??[]).map(x=>[x.company_name||`${x.first_name} ${x.last_name}`.trim(),x.tax_id,x.phone,(balances.get(x.id)??0).toFixed(2)]).filter(row=>Number(row[3])>0));}
 if(exportType==="payables"){const[{data:suppliers},{data:movements}]=await Promise.all([c.supabase.from("suppliers").select("id,name,tax_id,phone").eq("organization_id",c.organization.id),c.supabase.from("supplier_account_movements").select("supplier_id,type,amount").eq("organization_id",c.organization.id)]);const balances=new Map<string,number>();(movements??[]).forEach(x=>balances.set(x.supplier_id,(balances.get(x.supplier_id)??0)+(x.type==="charge"?Number(x.amount):-Number(x.amount))));body=csv(["Proveedor","NIT","Teléfono","Saldo"],(suppliers??[]).map(x=>[x.name,x.tax_id,x.phone,(balances.get(x.id)??0).toFixed(2)]).filter(row=>Number(row[3])>0));}
 const stamp=new Date().toISOString().slice(0,10);return new Response(body,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="stm-${exportType}-${stamp}.csv"`,"Cache-Control":"private, no-store"}})}
