import Link from "next/link";
import { ArrowLeft, Boxes, CircleDollarSign, PackageSearch, TrendingUp } from "lucide-react";
import { getOrganizationContext } from "@/lib/auth/organization";

export default async function InventoryValuationPage() {
  const context = await getOrganizationContext();
  if (!["owner", "admin", "manager", "inventory", "viewer"].includes(context.role)) return <main>Acceso restringido</main>;
  const { data: products, error } = await context.supabase.from("products")
    .select("id,name,sku,cost,price,active,category:categories(name),inventory_levels(quantity,reorder_point,location_id)")
    .eq("organization_id", context.organization.id).eq("active", true).order("name");
  if (error) throw new Error("No se pudo valorar el inventario.");
  const rows = (products ?? []).map((product) => {
    const level = (product.inventory_levels as Array<{ quantity: string | number; reorder_point: string | number; location_id: string }> ?? []).find((item) => item.location_id === context.location.id);
    const categoryValue = product.category as { name?: string } | Array<{ name?: string }> | null;
    const quantity = Number(level?.quantity ?? 0), cost = Number(product.cost), price = Number(product.price);
    return { id: product.id, name: product.name, sku: product.sku, category: (Array.isArray(categoryValue) ? categoryValue[0]?.name : categoryValue?.name) ?? "Sin categoría", quantity, reorderPoint: Number(level?.reorder_point ?? 0), cost, price, costValue: quantity * cost, saleValue: quantity * price };
  });
  const costValue = rows.reduce((sum, row) => sum + row.costValue, 0), saleValue = rows.reduce((sum, row) => sum + row.saleValue, 0), potentialMargin = saleValue - costValue;
  const lowStock = rows.filter((row) => row.quantity <= row.reorderPoint).length, outOfStock = rows.filter((row) => row.quantity <= 0).length;
  const currency = context.organization.currency_code === "GTQ" ? "Q" : context.organization.currency_code;
  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-7xl justify-between px-6 py-5 lg:px-10"><div><p className="font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Valoración · {context.location.name}</p></div><Link href="/" className="flex items-center gap-2"><ArrowLeft size={16} />Panel</Link></div></header><div className="mx-auto max-w-7xl space-y-7 px-6 py-9 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#517064]">Inventario</p><h1 className="mt-2 text-4xl font-bold">Valoración de existencias</h1><p className="mt-2 text-[#68766f]">Valores calculados con costo y precio actuales.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Valor al costo" value={`${currency} ${costValue.toFixed(2)}`} icon={CircleDollarSign}/><Metric label="Valor de venta" value={`${currency} ${saleValue.toFixed(2)}`} icon={TrendingUp}/><Metric label="Margen potencial" value={`${currency} ${potentialMargin.toFixed(2)}`} icon={TrendingUp}/><Metric label="Stock bajo" value={String(lowStock)} icon={PackageSearch}/><Metric label="Agotados" value={String(outOfStock)} icon={Boxes}/></section><section className="overflow-hidden rounded-2xl border border-black/8 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#edf0eb] text-xs uppercase"><tr><th className="p-4">Producto</th><th className="p-4">Categoría</th><th className="p-4 text-right">Existencia</th><th className="p-4 text-right">Costo</th><th className="p-4 text-right">Precio</th><th className="p-4 text-right">Valor costo</th><th className="p-4 text-right">Valor venta</th></tr></thead><tbody>{rows.sort((a,b)=>b.costValue-a.costValue).map(row=><tr key={row.id} className={`border-t ${row.quantity<=row.reorderPoint?"bg-amber-50/50":""}`}><td className="p-4"><strong>{row.name}</strong><p className="text-xs text-[#75837b]">{row.sku||"Sin SKU"}{row.quantity<=row.reorderPoint?" · Stock bajo":""}</p></td><td className="p-4">{row.category}</td><td className="p-4 text-right font-bold">{formatQuantity(row.quantity)}</td><td className="p-4 text-right">{currency} {row.cost.toFixed(2)}</td><td className="p-4 text-right">{currency} {row.price.toFixed(2)}</td><td className="p-4 text-right font-bold">{currency} {row.costValue.toFixed(2)}</td><td className="p-4 text-right font-bold text-[#285645]">{currency} {row.saleValue.toFixed(2)}</td></tr>)}</tbody></table></div></section></div></main>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Boxes}){return <article className="rounded-2xl border border-black/8 bg-white p-5"><div className="flex justify-between text-sm text-[#617069]"><span>{label}</span><Icon size={18}/></div><p className="mt-5 text-2xl font-bold">{value}</p></article>}
function formatQuantity(value:number){return value.toFixed(3).replace(/\.000$/,"").replace(/(\.\d*[1-9])0+$/,"$1")}
