import Link from "next/link";
import { ArrowLeft, Building2, CheckCircle2, ReceiptText, UserRound } from "lucide-react";
import { getOrganizationContext } from "@/lib/auth/organization";
import { updateOrganization, updateProfile } from "./actions";

const input = "h-11 w-full rounded-xl border border-black/10 bg-white px-3 outline-none focus:border-[#3e735e]";
const field = (label: string, name: string, value: string | null | undefined, options?: { type?: string; required?: boolean }) => <label><span className="mb-1.5 block text-sm font-semibold">{label}</span><input className={input} name={name} type={options?.type} defaultValue={value ?? ""} required={options?.required} /></label>;

export default async function SettingsPage({ searchParams }: PageProps<"/configuracion">) {
  const context = await getOrganizationContext();
  const params = await searchParams;
  const [{ data: profile }, { data: settings }] = await Promise.all([
    context.supabase.from("profiles").select("full_name, phone").eq("id", context.user.id).single(),
    context.supabase.from("organizations").select("tax_id, address, phone, email, receipt_footer").eq("id", context.organization.id).single(),
  ]);
  const canEditOrganization = ["owner","admin"].includes(context.role);
  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-5xl items-center gap-4 px-6 py-5"><Link href="/" className="grid size-10 place-items-center rounded-full border border-black/10"><ArrowLeft size={18} /></Link><div><p className="text-sm text-[#68766f]">{context.organization.name}</p><h1 className="text-xl font-bold">Configuración</h1></div></div></header><div className="mx-auto max-w-5xl space-y-6 px-6 py-9"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#517064]">Preferencias</p><h2 className="mt-2 text-4xl font-bold tracking-[-0.04em]">Empresa y cuenta</h2></div>{params.saved && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18} /> Cambios guardados correctamente.</p>}{params.error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">No fue posible guardar los cambios. Revisa los datos y permisos.</p>}
    <form action={updateProfile} className="rounded-2xl border border-black/8 bg-white p-6"><h3 className="flex items-center gap-2 text-lg font-bold"><UserRound size={19} /> Mi perfil</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("Nombre completo","fullName",profile?.full_name,{required:true})}{field("Teléfono","profilePhone",profile?.phone)}<button className="h-11 rounded-xl bg-[#163f32] font-bold text-white sm:col-span-2">Guardar perfil</button></div></form>
    <form action={updateOrganization} className={`rounded-2xl border border-black/8 bg-white p-6 ${!canEditOrganization ? "pointer-events-none opacity-60" : ""}`}><h3 className="flex items-center gap-2 text-lg font-bold"><Building2 size={19} /> Datos de la empresa</h3>{!canEditOrganization && <p className="mt-2 text-sm text-[#68766f]">Solo propietarios y administradores pueden modificar estos datos.</p>}<fieldset disabled={!canEditOrganization} className="mt-5 grid gap-4 sm:grid-cols-2">{field("Nombre comercial","name",context.organization.name,{required:true})}{field("NIT / identificación fiscal","taxId",settings?.tax_id)}{field("Teléfono","phone",settings?.phone)}{field("Correo","email",settings?.email,{type:"email"})}<label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-semibold">Dirección</span><input className={input} name="address" defaultValue={settings?.address ?? ""} /></label><label><span className="mb-1.5 block text-sm font-semibold">Moneda</span><select className={input} name="currency" defaultValue={context.organization.currency_code}><option value="GTQ">GTQ · Quetzal</option><option value="USD">USD · Dólar</option><option value="MXN">MXN · Peso mexicano</option></select></label><label><span className="mb-1.5 block text-sm font-semibold">Zona horaria</span><select className={input} name="timezone" defaultValue={context.organization.timezone}><option value="America/Guatemala">Guatemala</option><option value="America/Mexico_City">Ciudad de México</option><option value="America/New_York">Nueva York</option><option value="UTC">UTC</option></select></label><label className="sm:col-span-2"><span className="mb-1.5 flex items-center gap-2 text-sm font-semibold"><ReceiptText size={15} /> Mensaje al pie del recibo</span><textarea name="receiptFooter" maxLength={300} required defaultValue={settings?.receipt_footer ?? "Gracias por su compra."} className="min-h-24 w-full rounded-xl border border-black/10 p-3 outline-none focus:border-[#3e735e]" /></label><button className="h-11 rounded-xl bg-[#163f32] font-bold text-white sm:col-span-2">Guardar empresa</button></fieldset></form>
  </div></main>;
}
