import Link from "next/link";
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, Boxes, CalendarDays, ExternalLink } from "lucide-react";
import { getOrganizationContext } from "@/lib/auth/organization";

const datePattern = /^\d{4}-\d{2}-\d{2}$/;

export default async function MovementsPage({ searchParams }: PageProps<"/movimientos">) {
  const context = await getOrganizationContext();
  if (!["owner","admin","manager","inventory","viewer"].includes(context.role)) return <main className="grid min-h-screen place-items-center bg-[#f4f5f1] text-red-700">Tu rol no permite consultar movimientos de inventario.</main>;
  const params = await searchParams;
  const today = new Date().toLocaleDateString("en-CA", { timeZone: context.organization.timezone });
  const defaultFrom = new Date(`${today}T12:00:00Z`); defaultFrom.setUTCDate(defaultFrom.getUTCDate() - 30);
  const from = typeof params.from === "string" && datePattern.test(params.from) ? params.from : defaultFrom.toISOString().slice(0,10);
  const to = typeof params.to === "string" && datePattern.test(params.to) ? params.to : today;
  const productId = typeof params.product === "string" ? params.product : "";
  let movementQuery = context.supabase.from("inventory_movements").select("id, product_id, sale_id, quantity_delta, reason, created_at, product:products(name, sku)").eq("organization_id", context.organization.id).eq("location_id", context.location.id).gte("created_at", `${from}T00:00:00`).lte("created_at", `${to}T23:59:59.999`).order("created_at", { ascending: false }).limit(500);
  if (productId) movementQuery = movementQuery.eq("product_id", productId);
  const [{ data: movements, error }, { data: products }] = await Promise.all([movementQuery, context.supabase.from("products").select("id, name, sku").eq("organization_id", context.organization.id).order("name")]);
  if (error) throw new Error("No se pudo cargar el kardex.");
  const rows = movements ?? [];
  const entries = rows.filter((movement) => Number(movement.quantity_delta) > 0).reduce((sum, movement) => sum + Number(movement.quantity_delta), 0);
  const exits = Math.abs(rows.filter((movement) => Number(movement.quantity_delta) < 0).reduce((sum, movement) => sum + Number(movement.quantity_delta), 0));

  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="bg-[#163f32] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><div><p className="text-lg font-bold">{context.organization.name}</p><p className="text-xs text-white/60">Kardex · {context.location.name}</p></div><Link href="/" className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold"><ArrowLeft size={16} /> Panel</Link></div></header><div className="mx-auto max-w-7xl space-y-6 px-6 py-9 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#517064]">Auditoría</p><h1 className="mt-2 text-4xl font-bold tracking-[-0.04em]">Movimientos de inventario</h1><p className="mt-2 text-[#68766f]">Entradas y salidas generadas por todas las operaciones.</p></div><form className="grid gap-2 rounded-2xl border border-black/8 bg-white p-3 sm:grid-cols-3"><DateField label="Desde" name="from" value={from} /><DateField label="Hasta" name="to" value={to} /><label><span className="mb-1 block text-xs font-semibold">Producto</span><select name="product" defaultValue={productId} className="h-10 max-w-52 rounded-lg border border-black/10 bg-white px-2 text-sm"><option value="">Todos</option>{products?.map((product) => <option key={product.id} value={product.id}>{product.name}{product.sku ? ` · ${product.sku}` : ""}</option>)}</select></label><button className="h-10 rounded-lg bg-[#163f32] px-4 text-sm font-bold text-white sm:col-span-3">Aplicar filtros</button></form></div>
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Movimientos" value={String(rows.length)} icon={CalendarDays} /><Metric label="Unidades de entrada" value={formatQuantity(entries)} icon={ArrowDownToLine} tone="text-emerald-700" /><Metric label="Unidades de salida" value={formatQuantity(exits)} icon={ArrowUpFromLine} tone="text-red-700" /></section>
    <section className="overflow-hidden rounded-2xl border border-black/8 bg-white"><div className="hidden grid-cols-[1.4fr_1.5fr_1fr_auto] gap-4 border-b border-black/8 bg-[#edf0eb] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#607067] md:grid"><span>Producto</span><span>Motivo</span><span>Fecha</span><span>Cantidad</span></div><div className="divide-y divide-black/8">{!rows.length && <div className="p-14 text-center text-[#728078]"><Boxes className="mx-auto mb-3" /><p>No hay movimientos en este período.</p></div>}{rows.map((movement) => { const productValue = movement.product as { name?: string; sku?: string | null } | Array<{ name?: string; sku?: string | null }> | null; const product = Array.isArray(productValue) ? productValue[0] : productValue; const quantity = Number(movement.quantity_delta); return <article key={movement.id} className="grid gap-3 px-5 py-4 text-sm md:grid-cols-[1.4fr_1.5fr_1fr_auto] md:items-center"><div><p className="font-bold">{product?.name ?? "Producto eliminado"}</p><p className="text-xs text-[#75837b]">{product?.sku || "Sin SKU"}</p></div><div><p>{movement.reason}</p>{movement.sale_id && <Link href={`/ventas/recibo/${movement.sale_id}`} className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-[#285645] hover:underline">Ver recibo <ExternalLink size={12} /></Link>}</div><p className="text-[#68766f]">{new Intl.DateTimeFormat("es-GT", { dateStyle:"medium", timeStyle:"short", timeZone:context.organization.timezone }).format(new Date(movement.created_at))}</p><strong className={`text-base ${quantity > 0 ? "text-emerald-700" : "text-red-700"}`}>{quantity > 0 ? "+" : ""}{formatQuantity(quantity)}</strong></article>; })}</div>{rows.length === 500 && <p className="border-t border-black/8 bg-amber-50 px-5 py-3 text-xs text-amber-800">Se muestran los 500 movimientos más recientes del rango.</p>}</section></div></main>;
}

function DateField({ label, name, value }:{ label:string; name:string; value:string }) { return <label><span className="mb-1 block text-xs font-semibold">{label}</span><input name={name} type="date" defaultValue={value} className="h-10 rounded-lg border border-black/10 px-2 text-sm" /></label>; }
function Metric({ label, value, icon:Icon, tone="text-[#39705b]" }:{ label:string; value:string; icon:typeof Boxes; tone?:string }) { return <article className="rounded-2xl border border-black/8 bg-white p-5"><div className="flex justify-between text-sm text-[#617069]"><span>{label}</span><Icon size={18} className={tone} /></div><p className={`mt-5 text-2xl font-bold ${tone}`}>{value}</p></article>; }
function formatQuantity(value:number) { return value.toFixed(3).replace(/\.000$/, "").replace(/(\.\d*[1-9])0+$/, "$1"); }
