import Link from "next/link";
import { ArrowLeft, Building2, CheckCircle2, MapPin, Phone } from "lucide-react";
import { canManageLocations, getOrganizationContext } from "@/lib/auth/organization";
import { createLocation, selectLocation, updateLocation } from "./actions";

const input = "h-10 w-full rounded-lg border border-black/10 bg-white px-3 text-sm outline-none focus:border-[#3e735e]";

export default async function LocationsPage({ searchParams }: PageProps<"/sucursales">) {
  const context = await getOrganizationContext();
  const params = await searchParams;
  const canManage = canManageLocations(context.role);
  const { data: allLocations } = await context.supabase.from("locations").select("id, name, address, phone, active, created_at").eq("organization_id", context.organization.id).order("created_at");
  const notice = params.created ? "Sucursal creada e inventario inicializado." : params.updated ? "Sucursal actualizada." : params.selected ? "Sucursal de trabajo cambiada." : "";

  return <main className="min-h-screen bg-[#f4f5f1] text-[#17251f]"><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-7xl items-center gap-4 px-6 py-5 lg:px-10"><Link href="/" className="grid size-10 place-items-center rounded-full border border-black/10"><ArrowLeft size={18} /></Link><div><p className="text-sm text-[#68766f]">{context.organization.name}</p><h1 className="text-xl font-bold">Sucursales</h1></div></div></header>
    <div className="mx-auto max-w-7xl px-6 py-9 lg:px-10"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#517064]">Ubicaciones</p><h2 className="mt-2 text-4xl font-bold tracking-[-0.04em]">Puntos de operación</h2><p className="mt-2 text-[#68766f]">La sucursal seleccionada determina dónde se registran ventas, compras, gastos y existencias.</p></div>
      {notice && <p className="mb-5 flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18} />{notice}</p>}{params.error && <p className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">No fue posible realizar el cambio. Debe existir al menos una sucursal activa y los nombres no pueden repetirse.</p>}
      <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section className="space-y-4">{allLocations?.map((location) => { const selected = location.id === context.location.id; return <article key={location.id} className={`rounded-2xl border bg-white p-5 ${selected ? "border-[#3e735e] ring-4 ring-[#3e735e]/8" : "border-black/8"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${location.active ? "bg-[#e5ece7] text-[#285645]" : "bg-gray-100 text-gray-400"}`}><Building2 size={20} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{location.name}</h3>{selected && <span className="rounded-full bg-[#163f32] px-2.5 py-1 text-xs font-bold text-white">En uso</span>}{!location.active && <span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-bold text-gray-500">Inactiva</span>}</div>{location.address && <p className="mt-2 flex gap-2 text-sm text-[#68766f]"><MapPin size={15} />{location.address}</p>}{location.phone && <p className="mt-1 flex gap-2 text-sm text-[#68766f]"><Phone size={15} />{location.phone}</p>}</div>{location.active && !selected && <form action={selectLocation}><input type="hidden" name="locationId" value={location.id} /><button className="h-10 rounded-lg bg-[#d7f36b] px-4 text-sm font-bold text-[#163f32]">Usar sucursal</button></form>}</div>
          {canManage && <details className="mt-4 border-t border-black/7 pt-4"><summary className="cursor-pointer text-sm font-bold text-[#285645]">Editar sucursal</summary><form action={updateLocation} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="locationId" value={location.id} /><label><span className="mb-1 block text-xs font-semibold">Nombre</span><input className={input} name="name" defaultValue={location.name} required /></label><label><span className="mb-1 block text-xs font-semibold">Teléfono</span><input className={input} name="phone" defaultValue={location.phone ?? ""} /></label><label className="sm:col-span-2"><span className="mb-1 block text-xs font-semibold">Dirección</span><input className={input} name="address" defaultValue={location.address ?? ""} /></label>{location.active ? <><button name="active" value="true" className="h-10 rounded-lg bg-[#163f32] px-4 text-sm font-bold text-white">Guardar cambios</button><button name="active" value="false" className="h-10 rounded-lg bg-red-50 px-4 text-sm font-bold text-red-700">Desactivar</button></> : <button name="active" value="true" className="h-10 rounded-lg bg-emerald-50 px-4 text-sm font-bold text-emerald-700 sm:col-span-2">Guardar y activar</button>}</form></details>}
        </article>; })}</section>
        <aside>{canManage ? <form action={createLocation} className="rounded-2xl border border-black/8 bg-white p-5"><h3 className="font-bold">Nueva sucursal</h3><p className="mt-2 text-sm leading-6 text-[#68766f]">Los productos actuales se crearán con existencia cero.</p><div className="mt-5 space-y-3"><label><span className="mb-1 block text-xs font-semibold">Nombre</span><input className={input} name="name" required placeholder="Sucursal zona 10" /></label><label><span className="mb-1 block text-xs font-semibold">Dirección</span><input className={input} name="address" /></label><label><span className="mb-1 block text-xs font-semibold">Teléfono</span><input className={input} name="phone" /></label><button className="h-11 w-full rounded-xl bg-[#163f32] font-bold text-white">Crear sucursal</button></div></form> : <div className="rounded-2xl bg-white p-5 text-sm text-[#68766f]">Puedes cambiar tu sucursal activa. Solo gerentes y administradores pueden crear o editar ubicaciones.</div>}</aside></div>
    </div></main>;
}
